import { Suspense } from "react";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Loading from "./loading";
import SideBar from "@/layout/home/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={inter.className}
        style={{
          position: "relative",
          display: "flex",
          height: "100vh",
        }}
      >
        <Suspense fallback={<Loading />}>
          <SideBar />
        </Suspense>
        <Suspense fallback={<Loading />}>
          <section className="flex-1">{children}</section>
        </Suspense>
      </body>
    </html>
  );
}
